name: Semgrep

on:
  pull_request:
  push:
    branches:
      - develop
      - main

jobs:
  semgrep:
    name: Semgrep
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Semgrep
        run: pip install semgrep

      - name: Clone Frappe Semgrep rules
        run: git clone --depth 1 https://github.com/frappe/semgrep-rules.git frappe-semgrep-rules

      - name: Run Semgrep
        run: semgrep ci --config ./frappe-semgrep-rules/rules --config r/python.lang.correctness
